language: node_js  #设置语言

cache:
  directories:
  - node_modules

node_js: stable  #设置相应的版本

addons:
  ssh_known_hosts: git.coding.net

before_install:
# 替换为刚才生成的解密信息
- openssl aes-256-cbc -K $encrypted_669a544d2f37_key -iv $encrypted_669a544d2f37_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/id_rsa
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config

install:

  - npm install  #安装hexo及插件

script:
  #- node push.js $cnBlogName $cnBlogPwd
  - hexo cl  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "wjkang"  #修改name
  - git config user.email "977865769@qq.com"  #修改email
  - git add .
  - git commit -m "Travis CI Build"
  #- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
  #- git push --force --quiet "${CODING_REF}" master:master

branches:
  only:
    - master  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/wjkang/wjkang.github.io.git  #设置GH_REF，注意更改yourname
   - CODING_REF: git@git.coding.net:jaycewu/jaycewu.coding.me.git